/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const GiftPackageId = IDL.Text;
export const ShareToken = IDL.Text;
export const ExtraSection = IDL.Record({
  'id' : IDL.Text,
  'content' : IDL.Text,
  'sectionType' : IDL.Text,
  'sectionLabel' : IDL.Text,
});
export const GiftPackageContent = IDL.Record({
  'id' : GiftPackageId,
  'memeId' : IDL.Text,
  'status' : IDL.Variant({ 'published' : IDL.Null, 'draft' : IDL.Null }),
  'title' : IDL.Text,
  'songId' : IDL.Text,
  'createdAt' : IDL.Int,
  'voiceNoteUrl' : IDL.Text,
  'shareToken' : ShareToken,
  'creatorId' : IDL.Principal,
  'photoUrl' : IDL.Text,
  'updatedAt' : IDL.Int,
  'bgMusicId' : IDL.Text,
  'message' : IDL.Text,
  'gameType' : IDL.Text,
  'themeId' : IDL.Text,
  'extraSections' : IDL.Vec(ExtraSection),
});
export const CreatorSettings = IDL.Record({
  'customSectionLabels' : IDL.Vec(IDL.Text),
  'stepOrder' : IDL.Vec(IDL.Text),
});
export const QuizQuestion = IDL.Record({
  'id' : IDL.Text,
  'imageUrls' : IDL.Vec(IDL.Text),
  'correctIndex' : IDL.Nat,
  'questionText' : IDL.Text,
  'aiSuggested' : IDL.Bool,
  'choices' : IDL.Vec(IDL.Text),
});
export const QuizData = IDL.Record({ 'questions' : IDL.Vec(QuizQuestion) });
export const Challenge = IDL.Record({
  'id' : IDL.Text,
  'rewardMessage' : IDL.Text,
  'challengeType' : IDL.Text,
  'prompt' : IDL.Text,
});
export const ChallengeData = IDL.Record({ 'challenges' : IDL.Vec(Challenge) });
export const PackageExtras = IDL.Record({
  'quiz' : QuizData,
  'challengeData' : ChallengeData,
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createPackage' : IDL.Func(
      [IDL.Text],
      [IDL.Variant({ 'ok' : GiftPackageContent, 'err' : IDL.Text })],
      [],
    ),
  'deletePackage' : IDL.Func(
      [GiftPackageId],
      [IDL.Variant({ 'ok' : IDL.Bool, 'err' : IDL.Text })],
      [],
    ),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getCreatorSettings' : IDL.Func([], [CreatorSettings], ['query']),
  'getPackage' : IDL.Func(
      [GiftPackageId],
      [IDL.Variant({ 'ok' : GiftPackageContent, 'err' : IDL.Text })],
      ['query'],
    ),
  'getPackageByToken' : IDL.Func(
      [ShareToken],
      [IDL.Variant({ 'ok' : GiftPackageContent, 'err' : IDL.Text })],
      ['query'],
    ),
  'getPackageExtras' : IDL.Func(
      [GiftPackageId],
      [IDL.Variant({ 'ok' : PackageExtras, 'err' : IDL.Text })],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'listMyPackages' : IDL.Func([], [IDL.Vec(GiftPackageContent)], ['query']),
  'publishPackage' : IDL.Func(
      [GiftPackageId],
      [IDL.Variant({ 'ok' : IDL.Text, 'err' : IDL.Text })],
      [],
    ),
  'suggestQuizQuestions' : IDL.Func([IDL.Text], [IDL.Vec(IDL.Text)], ['query']),
  'updateCreatorSettings' : IDL.Func(
      [CreatorSettings],
      [IDL.Variant({ 'ok' : IDL.Bool, 'err' : IDL.Text })],
      [],
    ),
  'updatePackage' : IDL.Func(
      [
        GiftPackageId,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Vec(ExtraSection),
      ],
      [IDL.Variant({ 'ok' : GiftPackageContent, 'err' : IDL.Text })],
      [],
    ),
  'updatePackageExtras' : IDL.Func(
      [GiftPackageId, QuizData, ChallengeData],
      [IDL.Variant({ 'ok' : IDL.Bool, 'err' : IDL.Text })],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const GiftPackageId = IDL.Text;
  const ShareToken = IDL.Text;
  const ExtraSection = IDL.Record({
    'id' : IDL.Text,
    'content' : IDL.Text,
    'sectionType' : IDL.Text,
    'sectionLabel' : IDL.Text,
  });
  const GiftPackageContent = IDL.Record({
    'id' : GiftPackageId,
    'memeId' : IDL.Text,
    'status' : IDL.Variant({ 'published' : IDL.Null, 'draft' : IDL.Null }),
    'title' : IDL.Text,
    'songId' : IDL.Text,
    'createdAt' : IDL.Int,
    'voiceNoteUrl' : IDL.Text,
    'shareToken' : ShareToken,
    'creatorId' : IDL.Principal,
    'photoUrl' : IDL.Text,
    'updatedAt' : IDL.Int,
    'bgMusicId' : IDL.Text,
    'message' : IDL.Text,
    'gameType' : IDL.Text,
    'themeId' : IDL.Text,
    'extraSections' : IDL.Vec(ExtraSection),
  });
  const CreatorSettings = IDL.Record({
    'customSectionLabels' : IDL.Vec(IDL.Text),
    'stepOrder' : IDL.Vec(IDL.Text),
  });
  const QuizQuestion = IDL.Record({
    'id' : IDL.Text,
    'imageUrls' : IDL.Vec(IDL.Text),
    'correctIndex' : IDL.Nat,
    'questionText' : IDL.Text,
    'aiSuggested' : IDL.Bool,
    'choices' : IDL.Vec(IDL.Text),
  });
  const QuizData = IDL.Record({ 'questions' : IDL.Vec(QuizQuestion) });
  const Challenge = IDL.Record({
    'id' : IDL.Text,
    'rewardMessage' : IDL.Text,
    'challengeType' : IDL.Text,
    'prompt' : IDL.Text,
  });
  const ChallengeData = IDL.Record({ 'challenges' : IDL.Vec(Challenge) });
  const PackageExtras = IDL.Record({
    'quiz' : QuizData,
    'challengeData' : ChallengeData,
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createPackage' : IDL.Func(
        [IDL.Text],
        [IDL.Variant({ 'ok' : GiftPackageContent, 'err' : IDL.Text })],
        [],
      ),
    'deletePackage' : IDL.Func(
        [GiftPackageId],
        [IDL.Variant({ 'ok' : IDL.Bool, 'err' : IDL.Text })],
        [],
      ),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getCreatorSettings' : IDL.Func([], [CreatorSettings], ['query']),
    'getPackage' : IDL.Func(
        [GiftPackageId],
        [IDL.Variant({ 'ok' : GiftPackageContent, 'err' : IDL.Text })],
        ['query'],
      ),
    'getPackageByToken' : IDL.Func(
        [ShareToken],
        [IDL.Variant({ 'ok' : GiftPackageContent, 'err' : IDL.Text })],
        ['query'],
      ),
    'getPackageExtras' : IDL.Func(
        [GiftPackageId],
        [IDL.Variant({ 'ok' : PackageExtras, 'err' : IDL.Text })],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'listMyPackages' : IDL.Func([], [IDL.Vec(GiftPackageContent)], ['query']),
    'publishPackage' : IDL.Func(
        [GiftPackageId],
        [IDL.Variant({ 'ok' : IDL.Text, 'err' : IDL.Text })],
        [],
      ),
    'suggestQuizQuestions' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(IDL.Text)],
        ['query'],
      ),
    'updateCreatorSettings' : IDL.Func(
        [CreatorSettings],
        [IDL.Variant({ 'ok' : IDL.Bool, 'err' : IDL.Text })],
        [],
      ),
    'updatePackage' : IDL.Func(
        [
          GiftPackageId,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Vec(ExtraSection),
        ],
        [IDL.Variant({ 'ok' : GiftPackageContent, 'err' : IDL.Text })],
        [],
      ),
    'updatePackageExtras' : IDL.Func(
        [GiftPackageId, QuizData, ChallengeData],
        [IDL.Variant({ 'ok' : IDL.Bool, 'err' : IDL.Text })],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };