/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Challenge {
  'id' : string,
  'rewardMessage' : string,
  'challengeType' : string,
  'prompt' : string,
}
export interface ChallengeData { 'challenges' : Array<Challenge> }
export interface CreatorSettings {
  'customSectionLabels' : Array<string>,
  'stepOrder' : Array<string>,
}
export interface ExtraSection {
  'id' : string,
  'content' : string,
  'sectionType' : string,
  'sectionLabel' : string,
}
export interface GiftPackageContent {
  'id' : GiftPackageId,
  'memeId' : string,
  'status' : { 'published' : null } |
    { 'draft' : null },
  'title' : string,
  'songId' : string,
  'createdAt' : bigint,
  'voiceNoteUrl' : string,
  'shareToken' : ShareToken,
  'creatorId' : Principal,
  'photoUrl' : string,
  'updatedAt' : bigint,
  'bgMusicId' : string,
  'message' : string,
  'gameType' : string,
  'themeId' : string,
  'extraSections' : Array<ExtraSection>,
}
export type GiftPackageId = string;
export interface PackageExtras {
  'quiz' : QuizData,
  'challengeData' : ChallengeData,
}
export interface QuizData { 'questions' : Array<QuizQuestion> }
export interface QuizQuestion {
  'id' : string,
  'imageUrls' : Array<string>,
  'correctIndex' : bigint,
  'questionText' : string,
  'aiSuggested' : boolean,
  'choices' : Array<string>,
}
export type ShareToken = string;
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createPackage' : ActorMethod<
    [string],
    { 'ok' : GiftPackageContent } |
      { 'err' : string }
  >,
  'deletePackage' : ActorMethod<
    [GiftPackageId],
    { 'ok' : boolean } |
      { 'err' : string }
  >,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getCreatorSettings' : ActorMethod<[], CreatorSettings>,
  'getPackage' : ActorMethod<
    [GiftPackageId],
    { 'ok' : GiftPackageContent } |
      { 'err' : string }
  >,
  'getPackageByToken' : ActorMethod<
    [ShareToken],
    { 'ok' : GiftPackageContent } |
      { 'err' : string }
  >,
  'getPackageExtras' : ActorMethod<
    [GiftPackageId],
    { 'ok' : PackageExtras } |
      { 'err' : string }
  >,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'listMyPackages' : ActorMethod<[], Array<GiftPackageContent>>,
  'publishPackage' : ActorMethod<
    [GiftPackageId],
    { 'ok' : string } |
      { 'err' : string }
  >,
  'suggestQuizQuestions' : ActorMethod<[string], Array<string>>,
  'updateCreatorSettings' : ActorMethod<
    [CreatorSettings],
    { 'ok' : boolean } |
      { 'err' : string }
  >,
  'updatePackage' : ActorMethod<
    [
      GiftPackageId,
      string,
      string,
      string,
      string,
      string,
      string,
      string,
      string,
      string,
      Array<ExtraSection>,
    ],
    { 'ok' : GiftPackageContent } |
      { 'err' : string }
  >,
  'updatePackageExtras' : ActorMethod<
    [GiftPackageId, QuizData, ChallengeData],
    { 'ok' : boolean } |
      { 'err' : string }
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];